---
services:
  runner:
    image: github-runner-lnx:latest
    platform: linux
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
      args:
        RUNNER_VERSION: '2.335.1'
    volumes:
      - type: bind
        source: ./.env
        target: /home/docker/.env
