---
services:
  runner:
    image: github-runner-lnx:latest
    platform: linux
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: .
    volumes:
      - ./.env:/home/docker/.env
        
